name: Build documentation

on:
  push:
    branches:
      - release
      - doc-builder*

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: deep-rl-class
      path_to_docs: course/units/
      additional_args: --not_python_module
      languages: en
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}